const STYLES = String.raw`
:root{color-scheme:light dark;--bg:#fff;--fg:#17202a;--muted:#52606d;--card:#f5f7fa;--line:#d6dde5;--accent:#165dba;--focus:#ffbf47;--danger:#9b1c1c;--notice:#fff7df;font:16px/1.5 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
@media(prefers-color-scheme:dark){:root:not([data-theme="light"]){--bg:#101820;--fg:#f4f7fa;--muted:#bac6d1;--card:#1c2834;--line:#41505e;--accent:#8fc3ff;--focus:#ffd166;--danger:#ffb4ab;--notice:#3b3117}}
:root[data-theme="dark"]{color-scheme:dark;--bg:#101820;--fg:#f4f7fa;--muted:#bac6d1;--card:#1c2834;--line:#41505e;--accent:#8fc3ff;--focus:#ffd166;--danger:#ffb4ab;--notice:#3b3117}:root[data-theme="light"]{color-scheme:light}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg)}main{max-width:900px;margin:auto;padding:max(16px,env(safe-area-inset-top)) max(16px,env(safe-area-inset-right)) max(24px,env(safe-area-inset-bottom)) max(16px,env(safe-area-inset-left))}h1{font-size:clamp(1.45rem,4vw,2rem);line-height:1.2;margin:.2rem 0}.sub,.muted{color:var(--muted)}.toolbar{display:flex;gap:.6rem;flex-wrap:wrap;margin:1rem 0}button{font:inherit;font-weight:650;border:1px solid var(--line);border-radius:.55rem;background:var(--card);color:var(--fg);padding:.55rem .8rem;cursor:pointer}button.primary{background:var(--accent);color:#fff;border-color:var(--accent)}button:focus-visible,summary:focus-visible,input:focus-visible{outline:3px solid var(--focus);outline-offset:2px}.status{padding:1rem;border:1px solid var(--line);border-radius:.7rem;background:var(--card)}.status.error{color:var(--danger)}.notice{padding:.75rem 1rem;background:var(--notice);border-radius:.55rem;margin:.75rem 0}.hidden{display:none!important}.overview{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:.7rem;margin:1rem 0}.overview article,.row,.finding,.warning{background:var(--card);border:1px solid var(--line);border-radius:.65rem;padding:.8rem}.overview h2{font-size:1rem;margin:0 0 .4rem}.overview p{margin:0}.report-section{border-top:1px solid var(--line);padding:.5rem 0}.report-section>summary{font-size:1.15rem;font-weight:750;cursor:pointer;padding:.75rem 0}.report-section h3{font-size:1rem}.row,.finding,.warning{margin:.6rem 0}.row label{display:flex;gap:.65rem;align-items:flex-start}.row input{width:1.15rem;height:1.15rem;margin-top:.25rem}.tag{display:inline-block;border:1px solid currentColor;border-radius:99px;padding:.05rem .45rem;font-size:.78rem;margin-left:.4rem}.details{margin:.35rem 0 0;color:var(--muted)}ol,ul{padding-left:1.4rem}.follow{margin-top:.55rem;font-size:.9rem}footer{margin-top:1.5rem;color:var(--muted);font-size:.88rem}@media(max-width:480px){main{padding-inline:12px}.toolbar button{width:100%}}@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition:none!important}}@media print{.toolbar,.follow,.sub{display:none}.report-section{break-inside:avoid}.report-section>summary{list-style:none}}
`;

export function buildWidgetHtml(bundle: string): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Simplify Med report</title><style>${STYLES}</style></head>
<body><main id="app" aria-live="polite"><section class="status" role="status"><h1>Simplify Med report</h1><p>Waiting for the completed report from ChatGPT…</p></section></main><script>${bundle.replaceAll("</script", "<\\/script")}</script></body></html>`;
}
